# Generated by Django 2.1.7 on 2019-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='aview',
            field=models.TextField(default='none'),
        ),
    ]
