# Generated by Django 2.1.7 on 2019-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_music_aview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='aview',
            field=models.TextField(),
        ),
    ]
